"""Tests for markdown scan report generation."""

from __future__ import annotations

from pathlib import Path

import pytest

from agentward.scan.chains import ChainDetection, ChainRisk, detect_chains
from agentward.scan.config import ServerConfig, TransportType
from agentward.scan.enumerator import ToolInfo
from agentward.scan.permissions import (
    DataAccess,
    DataAccessType,
    RiskLevel,
    ScanResult,
    ServerPermissionMap,
    ToolPermission,
)
from agentward.scan.recommendations import Recommendation, RecommendationSeverity
from agentward.scan.report import generate_scan_markdown


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _tool(name: str) -> ToolInfo:
    return ToolInfo(name=name, description=f"Tool: {name}", input_schema={})


def _perm(
    name: str,
    risk: RiskLevel = RiskLevel.LOW,
    access: list[DataAccess] | None = None,
    destructive: bool = False,
) -> ToolPermission:
    return ToolPermission(
        tool=_tool(name),
        data_access=access or [],
        risk_level=risk,
        risk_reasons=["test"],
        is_destructive=destructive,
        is_read_only=not destructive,
    )


def _access(
    typ: DataAccessType,
    read: bool = True,
    write: bool = False,
) -> DataAccess:
    return DataAccess(type=typ, read=read, write=write, reason="test")


def _server(
    name: str,
    tools: list[ToolPermission],
    risk: RiskLevel = RiskLevel.LOW,
) -> ServerPermissionMap:
    return ServerPermissionMap(
        server=ServerConfig(
            name=name,
            transport=TransportType.STDIO,
            command="test",
            client="test",
            source_file=Path("/tmp/test.json"),
        ),
        enumeration_method="live",
        tools=tools,
        overall_risk=risk,
    )


def _scan(*servers: ServerPermissionMap) -> ScanResult:
    return ScanResult(
        servers=list(servers),
        config_sources=[],
    )


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestMarkdownReportStructure:
    """Verify the markdown report contains all required sections."""

    def test_header_present(self) -> None:
        scan = _scan(_server("test-server", [_perm("test-tool")]))
        md = generate_scan_markdown(scan, [])
        assert md.startswith("# AgentWard Scan Report")

    def test_version_present(self) -> None:
        import agentward

        scan = _scan(_server("test-server", [_perm("test-tool")]))
        md = generate_scan_markdown(scan, [])
        assert f"**AgentWard version:** {agentward.__version__}" in md

    def test_timestamp_present(self) -> None:
        scan = _scan(_server("test-server", [_perm("test-tool")]))
        md = generate_scan_markdown(scan, [])
        assert "**Generated:**" in md
        assert "UTC" in md

    def test_tools_scanned_count(self) -> None:
        scan = _scan(
            _server("s1", [_perm("t1"), _perm("t2")]),
            _server("s2", [_perm("t3")]),
        )
        md = generate_scan_markdown(scan, [])
        assert "**Tools scanned:** 3" in md

    def test_footer_present(self) -> None:
        scan = _scan(_server("test-server", [_perm("test-tool")]))
        md = generate_scan_markdown(scan, [])
        assert "Generated by [AgentWard](https://agentward.ai)" in md


class TestMarkdownPermissionMap:
    """Verify the permission map table is correct."""

    def test_table_header(self) -> None:
        scan = _scan(_server("test-server", [_perm("test-tool")]))
        md = generate_scan_markdown(scan, [])
        assert "## Permission Map" in md
        assert "| Source" in md
        assert "Tool/Skill" in md
        assert "Capabilities" in md
        assert "Risk" in md

    def test_tool_names_in_table(self) -> None:
        scan = _scan(_server("test-server", [
            _perm("read-email", risk=RiskLevel.LOW),
            _perm("send-email", risk=RiskLevel.HIGH),
        ]))
        md = generate_scan_markdown(scan, [])
        assert "`read-email`" in md
        assert "`send-email`" in md

    def test_risk_levels_in_table(self) -> None:
        scan = _scan(_server("test-server", [
            _perm("low-tool", risk=RiskLevel.LOW),
            _perm("critical-tool", risk=RiskLevel.CRITICAL),
        ]))
        md = generate_scan_markdown(scan, [])
        assert "LOW" in md
        assert "CRITICAL" in md


class TestMarkdownRiskSummary:
    """Verify the risk summary counts are correct."""

    def test_risk_counts(self) -> None:
        scan = _scan(_server("s1", [
            _perm("t1", risk=RiskLevel.CRITICAL),
            _perm("t2", risk=RiskLevel.CRITICAL),
            _perm("t3", risk=RiskLevel.HIGH),
            _perm("t4", risk=RiskLevel.LOW),
        ]))
        md = generate_scan_markdown(scan, [])
        assert "🔴 2 critical" in md
        assert "🟠 1 high" in md
        assert "🟢 1 low" in md

    def test_zero_counts_omitted(self) -> None:
        scan = _scan(_server("s1", [_perm("t1", risk=RiskLevel.LOW)]))
        md = generate_scan_markdown(scan, [])
        assert "critical" not in md
        assert "high" not in md
        assert "medium" not in md
        assert "🟢 1 low" in md


class TestMarkdownChains:
    """Verify chain output in the markdown report."""

    def test_no_chains_section_when_empty(self) -> None:
        scan = _scan(_server("s1", [_perm("t1")]))
        md = generate_scan_markdown(scan, [], chains=[])
        assert "## Skill Chains Detected" not in md

    def test_chains_section_present(self) -> None:
        chains = [
            ChainDetection(
                source_server="email-mgr",
                target_server="web-browser",
                risk=ChainRisk.HIGH,
                label="email-mgr → web-browser",
                description="Email content could leak via browsing",
                attack_vector="test",
            ),
        ]
        scan = _scan(_server("s1", [_perm("t1")]))
        md = generate_scan_markdown(scan, [], chains=chains)
        assert "## Skill Chains Detected" in md
        assert "`email-mgr → web-browser`" in md
        assert "Email content could leak via browsing" in md

    def test_chains_grouped(self) -> None:
        chains = [
            ChainDetection(
                source_server="bankr:trading",
                target_server="coding:shell",
                risk=ChainRisk.CRITICAL,
                label="bankr:trading → coding:shell",
                description="Network responses could trigger code execution",
                attack_vector="test",
            ),
            ChainDetection(
                source_server="bankr:transfers",
                target_server="coding:shell",
                risk=ChainRisk.CRITICAL,
                label="bankr:transfers → coding:shell",
                description="Network responses could trigger code execution",
                attack_vector="test",
            ),
        ]
        scan = _scan(_server("s1", [_perm("t1")]))
        md = generate_scan_markdown(scan, [], chains=chains)
        assert "(2 chains)" in md
        assert "`bankr` → `coding`" in md

    def test_chain_count_in_summary(self) -> None:
        chains = [
            ChainDetection(
                source_server="a",
                target_server="b",
                risk=ChainRisk.HIGH,
                label="a → b",
                description="test",
                attack_vector="test",
            ),
        ]
        scan = _scan(_server("s1", [_perm("t1")]))
        md = generate_scan_markdown(scan, [], chains=chains)
        assert "1 chain(s)" in md


class TestMarkdownRecommendations:
    """Verify recommendations appear in the report."""

    def test_no_recommendations_section_when_empty(self) -> None:
        scan = _scan(_server("s1", [_perm("t1")]))
        md = generate_scan_markdown(scan, [])
        assert "## Recommendations" not in md

    def test_recommendation_present(self) -> None:
        rec = Recommendation(
            severity=RecommendationSeverity.CRITICAL,
            target="test-server/shell-tool",
            message="Tool 'shell-tool' can execute shell commands.",
            suggested_policy="require_approval:\n  - shell-tool",
        )
        scan = _scan(_server("s1", [_perm("t1")]))
        md = generate_scan_markdown(scan, [rec])
        assert "## Recommendations" in md
        assert "CRITICAL" in md
        assert "shell commands" in md
        assert "```yaml" in md
        assert "require_approval:" in md

    def test_grouped_recommendations(self) -> None:
        recs = [
            Recommendation(
                severity=RecommendationSeverity.CRITICAL,
                target="s1/coding-agent:foo",
                message="Tool 'coding-agent:foo' can execute shell commands.",
                suggested_policy="require_approval:\n  - coding-agent:foo",
            ),
            Recommendation(
                severity=RecommendationSeverity.CRITICAL,
                target="s1/coding-agent:bar",
                message="Tool 'coding-agent:bar' can execute shell commands.",
                suggested_policy="require_approval:\n  - coding-agent:bar",
            ),
        ]
        scan = _scan(_server("s1", [_perm("t1")]))
        md = generate_scan_markdown(scan, recs)
        # Should be grouped, with both tools in one yaml block
        assert "coding-agent:foo" in md
        assert "coding-agent:bar" in md
        # Should NOT have two separate "### 1." and "### 2." — just one group
        assert "### 2." not in md


class TestMarkdownDeveloperFixes:
    """Verify the developer fixes section in the markdown report."""

    def test_no_fixes_for_low_risk(self) -> None:
        scan = _scan(_server("s1", [_perm("safe-tool", risk=RiskLevel.LOW)]))
        md = generate_scan_markdown(scan, [])
        assert "## Fixes for Skill Developers" not in md

    def test_fixes_present_for_high_risk(self) -> None:
        tool = _perm(
            "shell-exec",
            risk=RiskLevel.CRITICAL,
            access=[_access(DataAccessType.SHELL)],
        )
        # Inject realistic risk reasons
        tool.risk_reasons = ["Can execute shell commands"]
        scan = _scan(_server("s1", [tool]))
        md = generate_scan_markdown(scan, [])
        assert "## Fixes for Skill Developers" in md
        assert "Restrict execution" in md

    def test_fixes_grouped_by_parent(self) -> None:
        t1 = _perm("bankr:trading", risk=RiskLevel.HIGH)
        t1.risk_reasons = ["Financial operations — value transfer risk"]
        t2 = _perm("bankr:transfers", risk=RiskLevel.HIGH)
        t2.risk_reasons = ["Financial operations — value transfer risk"]
        scan = _scan(_server("s1", [t1, t2]))
        md = generate_scan_markdown(scan, [])
        assert "### `bankr`" in md
        # Both tools listed under the same fix
        assert "`bankr:trading`" in md
        assert "`bankr:transfers`" in md

    def test_financial_credential_fix(self) -> None:
        tool = _perm("bankr:betting", risk=RiskLevel.CRITICAL)
        tool.risk_reasons = [
            "Financial operations — value transfer risk",
            "Financial operations with credential access — direct value transfer risk",
        ]
        scan = _scan(_server("s1", [tool]))
        md = generate_scan_markdown(scan, [])
        assert "Separate credential management" in md
